### ISSUE TITLE
DOC HTML Syntax/Rendering Error in Section "Install the site assets"

### ISSUE THREAD

**Issue by LaurentAl** [google-developer-training/pwa-ecommerce-demo#19]
https://developers.google.com/web/fundamentals/codelabs/offline?hl=en#install_the_site_assets

![e](https://user-images.githubusercontent.com/42551847/65662606-fa134980-e034-11e9-976a-83d0fafce3d0.png)

**Comment by sarahec** [comment]
@LaurentAl Thank you for catching this. I see the issue in the markdown source and will fix it.

**Comment by sarahec** [comment]
Filed fix as https://github.com/google/WebFundamentals/pull/8175

**Comment by sarahec** [comment]
Change merged, so I'm closing the bug.
